name: Run Snowflake SQL Scripts

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the main branch
  workflow_dispatch:  # Allow manual workflow runs

jobs:
  run-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install schemachange
        run: pip install schemachange

      - name: Run SQL Scripts
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: |
          schemachange deploy \
            -a $SNOWFLAKE_ACCOUNT \
            -u $SNOWFLAKE_USER \
            -r $SNOWFLAKE_ROLE \
            -w $SNOWFLAKE_WAREHOUSE \
            -d $SNOWFLAKE_DATABASE \
            -s $SNOWFLAKE_SCHEMA \
            -f ./change-scripts
