name: Run Snowflake SQL Scripts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install schemachange
        run: pip install schemachange jq

      - name: Create Secure connections.toml
        env:
          SNOWFLAKE_SECRET: ${{ secrets.SNOWFLAKE_SECRET }}
        run: |
          echo "[default]" > connections.toml
          echo "account = \"$(echo $SNOWFLAKE_SECRET | jq -r .account)\"" >> connections.toml
          echo "user = \"$(echo $SNOWFLAKE_SECRET | jq -r .user)\"" >> connections.toml
          echo "password = \"$(echo $SNOWFLAKE_SECRET | jq -r .password)\"" >> connections.toml
          echo "role = \"$(echo $SNOWFLAKE_SECRET | jq -r .role)\"" >> connections.toml
          echo "warehouse = \"$(echo $SNOWFLAKE_SECRET | jq -r .warehouse)\"" >> connections.toml
          echo "database = \"$(echo $SNOWFLAKE_SECRET | jq -r .database)\"" >> connections.toml
          echo "schema = \"$(echo $SNOWFLAKE_SECRET | jq -r .schema)\"" >> connections.toml

      - name: Fix Permissions for connections.toml
        run: chmod 600 connections.toml

      - name: Run schemachange
        run: |
          schemachange deploy -c connections.toml

      - name: Cleanup connections.toml
        if: always()
        run: rm -f connections.toml
        run: rm -f connections.toml
