name: Run Snowflake SQL Scripts

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch
  workflow_dispatch:  # Allow manual runs

jobs:
  run-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install schemachange
        run: pip install schemachange

      - name: Run SQL Scripts with schemachange
        env:
          SNOWFLAKE_SECRET: ${{ secrets.SNOWFLAKE_SECRET }}
        run: |
          echo $SNOWFLAKE_SECRET > snowflake_config.json
          schemachange deploy \
            -a $(jq -r .SNOWFLAKE_ACCOUNT snowflake_config.json) \
            -u $(jq -r .SNOWFLAKE_USER snowflake_config.json) \
            -r $(jq -r .SNOWFLAKE_ROLE snowflake_config.json) \
            -w $(jq -r .SNOWFLAKE_WAREHOUSE snowflake_config.json) \
            -d $(jq -r .SNOWFLAKE_DATABASE snowflake_config.json) \
            -s $(jq -r .SNOWFLAKE_SCHEMA snowflake_config.json) \
            -f ./change-scripts
