name: Run Snowflake SQL Scripts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install schemachange
        run: pip install schemachange

      - name: Parse Snowflake Secret and Run SQL Scripts
        env:
          SNOWFLAKE_SECRET: ${{ secrets.SNOWFLAKE_SECRET }}
        run: |
          echo $SNOWFLAKE_SECRET > snowflake_config.json
          export SNOWFLAKE_ACCOUNT=$(jq -r .SNOWFLAKE_ACCOUNT snowflake_config.json)
          export SNOWFLAKE_USER=$(jq -r .SNOWFLAKE_USER snowflake_config.json)
          export SNOWFLAKE_PASSWORD=$(jq -r .SNOWFLAKE_PASSWORD snowflake_config.json)
          export SNOWFLAKE_ROLE=$(jq -r .SNOWFLAKE_ROLE snowflake_config.json)
          export SNOWFLAKE_WAREHOUSE=$(jq -r .SNOWFLAKE_WAREHOUSE snowflake_config.json)
          export SNOWFLAKE_DATABASE=$(jq -r .SNOWFLAKE_DATABASE snowflake_config.json)
          export SNOWFLAKE_SCHEMA=$(jq -r .SNOWFLAKE_SCHEMA snowflake_config.json)
          schemachange deploy \
            -a $SNOWFLAKE_ACCOUNT \
            -u $SNOWFLAKE_USER \
            -p $SNOWFLAKE_PASSWORD \
            -r $SNOWFLAKE_ROLE \
            -w $SNOWFLAKE_WAREHOUSE \
            -d $SNOWFLAKE_DATABASE \
            -s $SNOWFLAKE_SCHEMA \
            -f ./change-scripts
